import { IIconButtonProps } from "@/components/buttons/IconButtons";
import IconAppleBlackBg from "@/svg/apple/icon-black-bg";
import IconAppleBW from "@/svg/apple/icon-bw";
import IconAppleWhiteBg from "@/svg/apple/icon-white-bg";
import IconFacebook from "@/svg/facebook/icon-blue-bg";
import IconFacebookBW from "@/svg/facebook/icon-bw";
import IconFacebookWhiteBg from "@/svg/facebook/icon-white-bg";
import IconGoogleBW from "@/svg/google/icon-bw";
import IconGoogleColorful from "@/svg/google/icon-colorful";

export const ALL_ICON_BTNS: IIconButtonProps[][][] = [
  [
    [
      {
        backgroundColor: "#FFFFFF",
        borderColor: "#D0D5DD",
        foregroundColor: "#344054",
        icon: <IconGoogleColorful width={24} height={24} />,
        label: "Sign in with Google",
      },
      {
        backgroundColor: "#FFFFFF",
        borderColor: "#D0D5DD",
        foregroundColor: "#344054",
        icon: <IconGoogleColorful width={24} height={24} />,
      },
      {
        backgroundColor: "#FFFFFF",
        borderColor: "#D0D5DD",
        foregroundColor: "#344054",
        icon: <IconGoogleColorful width={24} height={24} />,
        label: "Sign in with Google",
      },
      {
        backgroundColor: "#FFFFFF",
        borderColor: "#D0D5DD",
        foregroundColor: "#344054",
        icon: <IconGoogleColorful width={24} height={24} />,
      },
      {
        backgroundColor: "#FFFFFF",
        borderColor: "#D0D5DD",
        foregroundColor: "#344054",
        icon: <IconGoogleBW width={24} height={24} />,
        label: "Sign in with Google",
      },
      {
        backgroundColor: "#FFFFFF",
        borderColor: "#D0D5DD",
        foregroundColor: "#344054",
        icon: <IconGoogleBW width={24} height={24} />,
      },
    ],
    [
      {
        backgroundColor: "#F9FAFB",
        borderColor: "#D0D5DD",
        foregroundColor: "#344054",
        icon: <IconGoogleColorful width={24} height={24} />,
        label: "Sign in with Google",
      },
      {
        backgroundColor: "#F9FAFB",
        borderColor: "#D0D5DD",
        foregroundColor: "#344054",
        icon: <IconGoogleColorful width={24} height={24} />,
      },
      {
        backgroundColor: "#F9FAFB",
        borderColor: "#D0D5DD",
        foregroundColor: "#344054",
        icon: <IconGoogleColorful width={24} height={24} />,
        label: "Sign in with Google",
      },
      {
        backgroundColor: "#F9FAFB",
        borderColor: "#D0D5DD",
        foregroundColor: "#344054",
        icon: <IconGoogleColorful width={24} height={24} />,
      },
      {
        backgroundColor: "#F9FAFB",
        borderColor: "#D0D5DD",
        foregroundColor: "#344054",
        icon: <IconGoogleBW width={24} height={24} />,
        label: "Sign in with Google",
      },
      {
        backgroundColor: "#F9FAFB",
        borderColor: "#D0D5DD",
        foregroundColor: "#344054",
        icon: <IconGoogleBW width={24} height={24} />,
      },
    ],
    [
      {
        backgroundColor: "#FFFFFF",
        borderColor: "#D0D5DD",
        foregroundColor: "#344054",
        icon: <IconGoogleColorful width={24} height={24} />,
        label: "Sign in with Google",
        shadow: true,
        shadowColor: "#F2F4F7",
      },
      {
        backgroundColor: "#FFFFFF",
        borderColor: "#D0D5DD",
        foregroundColor: "#344054",
        icon: <IconGoogleColorful width={24} height={24} />,
        shadow: true,
        shadowColor: "#F2F4F7",
      },
      {
        backgroundColor: "#FFFFFF",
        borderColor: "#D0D5DD",
        foregroundColor: "#344054",
        icon: <IconGoogleColorful width={24} height={24} />,
        label: "Sign in with Google",
        shadow: true,
        shadowColor: "#F2F4F7",
      },
      {
        backgroundColor: "#FFFFFF",
        borderColor: "#D0D5DD",
        foregroundColor: "#344054",
        icon: <IconGoogleColorful width={24} height={24} />,
        shadow: true,
        shadowColor: "#F2F4F7",
      },
      {
        backgroundColor: "#FFFFFF",
        borderColor: "#D0D5DD",
        foregroundColor: "#344054",
        icon: <IconGoogleBW width={24} height={24} />,
        label: "Sign in with Google",
        shadow: true,
        shadowColor: "#F2F4F7",
      },
      {
        backgroundColor: "#FFFFFF",
        borderColor: "#D0D5DD",
        foregroundColor: "#344054",
        icon: <IconGoogleBW width={24} height={24} />,
        shadow: true,
        shadowColor: "#F2F4F7",
      },
    ],
  ],
  [
    [
      {
        backgroundColor: "#1877F2",
        foregroundColor: "#FFFFFF",
        icon: <IconFacebookWhiteBg width={24} height={24} />,
        label: "Sign in with Facebook",
      },
      {
        backgroundColor: "#1877F2",
        foregroundColor: "#344054",
        icon: <IconFacebookWhiteBg width={24} height={24} />,
      },
      {
        backgroundColor: "#FFFFFF",
        borderColor: "#D0D5DD",
        foregroundColor: "#344054",
        icon: <IconFacebook width={24} height={24} />,
        label: "Sign in with Facebook",
      },
      {
        backgroundColor: "#FFFFFF",
        borderColor: "#D0D5DD",
        foregroundColor: "#344054",
        icon: <IconFacebook width={24} height={24} />,
      },
      {
        backgroundColor: "#FFFFFF",
        borderColor: "#D0D5DD",
        foregroundColor: "#344054",
        icon: <IconFacebookBW width={24} height={24} />,
        label: "Sign in with Facebook",
      },
      {
        backgroundColor: "#FFFFFF",
        borderColor: "#D0D5DD",
        foregroundColor: "#344054",
        icon: <IconFacebookBW width={24} height={24} />,
      },
    ],
    [
      {
        backgroundColor: "#0C63D4",
        foregroundColor: "#FFFFFF",
        icon: <IconFacebookWhiteBg width={24} height={24} />,
        label: "Sign in with Facebook",
      },
      {
        backgroundColor: "#0C63D4",
        foregroundColor: "#344054",
        icon: <IconFacebookWhiteBg width={24} height={24} />,
      },
      {
        backgroundColor: "#F9FAFB",
        borderColor: "#D0D5DD",
        foregroundColor: "#344054",
        icon: <IconFacebook width={24} height={24} />,
        label: "Sign in with Facebook",
      },
      {
        backgroundColor: "#F9FAFB",
        borderColor: "#D0D5DD",
        foregroundColor: "#344054",
        icon: <IconFacebook width={24} height={24} />,
      },
      {
        backgroundColor: "#F9FAFB",
        borderColor: "#D0D5DD",
        foregroundColor: "#344054",
        icon: <IconFacebookBW width={24} height={24} />,
        label: "Sign in with Facebook",
      },
      {
        backgroundColor: "#F9FAFB",
        borderColor: "#D0D5DD",
        foregroundColor: "#344054",
        icon: <IconFacebookBW width={24} height={24} />,
      },
    ],
    [
      {
        backgroundColor: "#1877F2",
        foregroundColor: "#FFFFFF",
        icon: <IconFacebookWhiteBg width={24} height={24} />,
        label: "Sign in with Facebook",
        shadow: true,
        shadowColor: "#F2F4F7",
      },
      {
        backgroundColor: "#1877F2",
        foregroundColor: "#344054",
        icon: <IconFacebookWhiteBg width={24} height={24} />,
        shadow: true,
        shadowColor: "#F2F4F7",
      },
      {
        backgroundColor: "#FFFFFF",
        borderColor: "#D0D5DD",
        foregroundColor: "#344054",
        icon: <IconFacebook width={24} height={24} />,
        label: "Sign in with Facebook",
        shadow: true,
        shadowColor: "#F2F4F7",
      },
      {
        backgroundColor: "#FFFFFF",
        borderColor: "#D0D5DD",
        foregroundColor: "#344054",
        icon: <IconFacebook width={24} height={24} />,
        shadow: true,
        shadowColor: "#F2F4F7",
      },
      {
        backgroundColor: "#FFFFFF",
        borderColor: "#D0D5DD",
        foregroundColor: "#344054",
        icon: <IconFacebookBW width={24} height={24} />,
        label: "Sign in with Facebook",
        shadow: true,
        shadowColor: "#F2F4F7",
      },
      {
        backgroundColor: "#FFFFFF",
        borderColor: "#D0D5DD",
        foregroundColor: "#344054",
        icon: <IconFacebookBW width={24} height={24} />,
        shadow: true,
        shadowColor: "#F2F4F7",
      },
    ],
  ],
  [
    [
      {
        backgroundColor: "#050505",
        foregroundColor: "#FFFFFF",
        icon: <IconAppleWhiteBg width={24} height={24} />,
        label: "Sign in with Apple",
      },
      {
        backgroundColor: "#050505",
        foregroundColor: "#FFFFFF",
        icon: <IconAppleWhiteBg width={24} height={24} />,
      },
      {
        backgroundColor: "#FFFFFF",
        borderColor: "#D0D5DD",
        foregroundColor: "#344054",
        icon: <IconAppleBlackBg width={24} height={24} />,
        label: "Sign in with Apple",
      },
      {
        backgroundColor: "#FFFFFF",
        borderColor: "#D0D5DD",
        foregroundColor: "#344054",
        icon: <IconAppleBlackBg width={24} height={24} />,
      },
      {
        backgroundColor: "#FFFFFF",
        borderColor: "#D0D5DD",
        foregroundColor: "#344054",
        icon: <IconAppleBW width={24} height={24} />,
        label: "Sign in with Apple",
      },
      {
        backgroundColor: "#FFFFFF",
        borderColor: "#D0D5DD",
        foregroundColor: "#344054",
        icon: <IconAppleBW width={24} height={24} />,
      },
    ],
    [
      {
        backgroundColor: "#050505",
        foregroundColor: "#FFFFFF",
        icon: <IconAppleWhiteBg width={24} height={24} />,
        label: "Sign in with Apple",
      },
      {
        backgroundColor: "#050505",
        foregroundColor: "#FFFFFF",
        icon: <IconAppleWhiteBg width={24} height={24} />,
      },
      {
        backgroundColor: "#F9FAFB",
        borderColor: "#D0D5DD",
        foregroundColor: "#344054",
        icon: <IconAppleBlackBg width={24} height={24} />,
        label: "Sign in with Apple",
      },
      {
        backgroundColor: "#F9FAFB",
        borderColor: "#D0D5DD",
        foregroundColor: "#344054",
        icon: <IconAppleBlackBg width={24} height={24} />,
      },
      {
        backgroundColor: "#F9FAFB",
        borderColor: "#D0D5DD",
        foregroundColor: "#344054",
        icon: <IconAppleBW width={24} height={24} />,
        label: "Sign in with Apple",
      },
      {
        backgroundColor: "#F9FAFB",
        borderColor: "#D0D5DD",
        foregroundColor: "#344054",
        icon: <IconAppleBW width={24} height={24} />,
      },
    ],
    [
      {
        backgroundColor: "#050505",
        foregroundColor: "#FFFFFF",
        icon: <IconAppleWhiteBg width={24} height={24} />,
        label: "Sign in with Apple",
        shadow: true,
        shadowColor: "#F2F4F7",
      },
      {
        backgroundColor: "#050505",
        foregroundColor: "#FFFFFF",
        icon: <IconAppleWhiteBg width={24} height={24} />,
        shadow: true,
        shadowColor: "#F2F4F7",
      },
      {
        backgroundColor: "#FFFFFF",
        borderColor: "#D0D5DD",
        foregroundColor: "#344054",
        icon: <IconAppleBlackBg width={24} height={24} />,
        label: "Sign in with Apple",
        shadow: true,
        shadowColor: "#F2F4F7",
      },
      {
        backgroundColor: "#FFFFFF",
        borderColor: "#D0D5DD",
        foregroundColor: "#344054",
        icon: <IconAppleBlackBg width={24} height={24} />,
        shadow: true,
        shadowColor: "#F2F4F7",
      },
      {
        backgroundColor: "#FFFFFF",
        borderColor: "#D0D5DD",
        foregroundColor: "#344054",
        icon: <IconAppleBW width={24} height={24} />,
        label: "Sign in with Apple",
        shadow: true,
        shadowColor: "#F2F4F7",
      },
      {
        backgroundColor: "#FFFFFF",
        borderColor: "#D0D5DD",
        foregroundColor: "#344054",
        icon: <IconAppleBW width={24} height={24} />,
        shadow: true,
        shadowColor: "#F2F4F7",
      },
    ],
  ],
];
