import { IIconButtonProps } from "@/components/buttons/IconButtons";
import IconGoogleBW from "@/svg/google/icon-bw";
import IconGoogleColorful from "@/svg/google/icon-colorful";

export const ALL_ICON_BTNS: IIconButtonProps[][][] = [
  [
    [
      {
        backgroundColor: "#FFFFFF",
        borderColor: "#D0D5DD",
        foregroundColor: "#344054",
        icon: <IconGoogleColorful width={24} height={24} />,
        label: "Sign in with Google",
      },
      {
        backgroundColor: "#FFFFFF",
        borderColor: "#D0D5DD",
        foregroundColor: "#344054",
        icon: <IconGoogleColorful width={24} height={24} />,
      },
      {
        backgroundColor: "#FFFFFF",
        borderColor: "#D0D5DD",
        foregroundColor: "#344054",
        icon: <IconGoogleColorful width={24} height={24} />,
        label: "Sign in with Google",
      },
      {
        backgroundColor: "#FFFFFF",
        borderColor: "#D0D5DD",
        foregroundColor: "#344054",
        icon: <IconGoogleColorful width={24} height={24} />,
      },
      {
        backgroundColor: "#FFFFFF",
        borderColor: "#D0D5DD",
        foregroundColor: "#344054",
        icon: <IconGoogleBW width={24} height={24} />,
        label: "Sign in with Google",
      },
      {
        backgroundColor: "#FFFFFF",
        borderColor: "#D0D5DD",
        foregroundColor: "#344054",
        icon: <IconGoogleBW width={24} height={24} />,
      },
    ],
    [
      {
        backgroundColor: "#FFFFFF",
        borderColor: "#D0D5DD",
        foregroundColor: "#344054",
        icon: <IconGoogleColorful width={24} height={24} />,
        label: "Sign in with Google",
      },
      {
        backgroundColor: "#FFFFFF",
        borderColor: "#D0D5DD",
        foregroundColor: "#344054",
        icon: <IconGoogleColorful width={24} height={24} />,
      },
      {
        backgroundColor: "#FFFFFF",
        borderColor: "#D0D5DD",
        foregroundColor: "#344054",
        icon: <IconGoogleColorful width={24} height={24} />,
        label: "Sign in with Google",
      },
      {
        backgroundColor: "#FFFFFF",
        borderColor: "#D0D5DD",
        foregroundColor: "#344054",
        icon: <IconGoogleColorful width={24} height={24} />,
      },
      {
        backgroundColor: "#FFFFFF",
        borderColor: "#D0D5DD",
        foregroundColor: "#344054",
        icon: <IconGoogleBW width={24} height={24} />,
        label: "Sign in with Google",
      },
      {
        backgroundColor: "#FFFFFF",
        borderColor: "#D0D5DD",
        foregroundColor: "#344054",
        icon: <IconGoogleBW width={24} height={24} />,
      },
    ],
    [
      {
        backgroundColor: "#FFFFFF",
        borderColor: "#D0D5DD",
        foregroundColor: "#344054",
        icon: <IconGoogleColorful width={24} height={24} />,
        label: "Sign in with Google",
      },
      {
        backgroundColor: "#FFFFFF",
        borderColor: "#D0D5DD",
        foregroundColor: "#344054",
        icon: <IconGoogleColorful width={24} height={24} />,
      },
      {
        backgroundColor: "#FFFFFF",
        borderColor: "#D0D5DD",
        foregroundColor: "#344054",
        icon: <IconGoogleColorful width={24} height={24} />,
        label: "Sign in with Google",
      },
      {
        backgroundColor: "#FFFFFF",
        borderColor: "#D0D5DD",
        foregroundColor: "#344054",
        icon: <IconGoogleColorful width={24} height={24} />,
      },
      {
        backgroundColor: "#FFFFFF",
        borderColor: "#D0D5DD",
        foregroundColor: "#344054",
        icon: <IconGoogleBW width={24} height={24} />,
        label: "Sign in with Google",
      },
      {
        backgroundColor: "#FFFFFF",
        borderColor: "#D0D5DD",
        foregroundColor: "#344054",
        icon: <IconGoogleBW width={24} height={24} />,
      },
    ],
  ],
  [
    [
      {
        backgroundColor: "#FFFFFF",
        borderColor: "#D0D5DD",
        foregroundColor: "#344054",
        icon: <IconGoogleColorful width={24} height={24} />,
        label: "Sign in with Google",
      },
      {
        backgroundColor: "#FFFFFF",
        borderColor: "#D0D5DD",
        foregroundColor: "#344054",
        icon: <IconGoogleColorful width={24} height={24} />,
      },
      {
        backgroundColor: "#FFFFFF",
        borderColor: "#D0D5DD",
        foregroundColor: "#344054",
        icon: <IconGoogleColorful width={24} height={24} />,
        label: "Sign in with Google",
      },
      {
        backgroundColor: "#FFFFFF",
        borderColor: "#D0D5DD",
        foregroundColor: "#344054",
        icon: <IconGoogleColorful width={24} height={24} />,
      },
      {
        backgroundColor: "#FFFFFF",
        borderColor: "#D0D5DD",
        foregroundColor: "#344054",
        icon: <IconGoogleBW width={24} height={24} />,
        label: "Sign in with Google",
      },
      {
        backgroundColor: "#FFFFFF",
        borderColor: "#D0D5DD",
        foregroundColor: "#344054",
        icon: <IconGoogleBW width={24} height={24} />,
      },
    ],
    [
      {
        backgroundColor: "#FFFFFF",
        borderColor: "#D0D5DD",
        foregroundColor: "#344054",
        icon: <IconGoogleColorful width={24} height={24} />,
        label: "Sign in with Google",
      },
      {
        backgroundColor: "#FFFFFF",
        borderColor: "#D0D5DD",
        foregroundColor: "#344054",
        icon: <IconGoogleColorful width={24} height={24} />,
      },
      {
        backgroundColor: "#FFFFFF",
        borderColor: "#D0D5DD",
        foregroundColor: "#344054",
        icon: <IconGoogleColorful width={24} height={24} />,
        label: "Sign in with Google",
      },
      {
        backgroundColor: "#FFFFFF",
        borderColor: "#D0D5DD",
        foregroundColor: "#344054",
        icon: <IconGoogleColorful width={24} height={24} />,
      },
      {
        backgroundColor: "#FFFFFF",
        borderColor: "#D0D5DD",
        foregroundColor: "#344054",
        icon: <IconGoogleBW width={24} height={24} />,
        label: "Sign in with Google",
      },
      {
        backgroundColor: "#FFFFFF",
        borderColor: "#D0D5DD",
        foregroundColor: "#344054",
        icon: <IconGoogleBW width={24} height={24} />,
      },
    ],
    [
      {
        backgroundColor: "#FFFFFF",
        borderColor: "#D0D5DD",
        foregroundColor: "#344054",
        icon: <IconGoogleColorful width={24} height={24} />,
        label: "Sign in with Google",
      },
      {
        backgroundColor: "#FFFFFF",
        borderColor: "#D0D5DD",
        foregroundColor: "#344054",
        icon: <IconGoogleColorful width={24} height={24} />,
      },
      {
        backgroundColor: "#FFFFFF",
        borderColor: "#D0D5DD",
        foregroundColor: "#344054",
        icon: <IconGoogleColorful width={24} height={24} />,
        label: "Sign in with Google",
      },
      {
        backgroundColor: "#FFFFFF",
        borderColor: "#D0D5DD",
        foregroundColor: "#344054",
        icon: <IconGoogleColorful width={24} height={24} />,
      },
      {
        backgroundColor: "#FFFFFF",
        borderColor: "#D0D5DD",
        foregroundColor: "#344054",
        icon: <IconGoogleBW width={24} height={24} />,
        label: "Sign in with Google",
      },
      {
        backgroundColor: "#FFFFFF",
        borderColor: "#D0D5DD",
        foregroundColor: "#344054",
        icon: <IconGoogleBW width={24} height={24} />,
      },
    ],
  ],
  [
    [
      {
        backgroundColor: "#FFFFFF",
        borderColor: "#D0D5DD",
        foregroundColor: "#344054",
        icon: <IconGoogleColorful width={24} height={24} />,
        label: "Sign in with Google",
      },
      {
        backgroundColor: "#FFFFFF",
        borderColor: "#D0D5DD",
        foregroundColor: "#344054",
        icon: <IconGoogleColorful width={24} height={24} />,
      },
      {
        backgroundColor: "#FFFFFF",
        borderColor: "#D0D5DD",
        foregroundColor: "#344054",
        icon: <IconGoogleColorful width={24} height={24} />,
        label: "Sign in with Google",
      },
      {
        backgroundColor: "#FFFFFF",
        borderColor: "#D0D5DD",
        foregroundColor: "#344054",
        icon: <IconGoogleColorful width={24} height={24} />,
      },
      {
        backgroundColor: "#FFFFFF",
        borderColor: "#D0D5DD",
        foregroundColor: "#344054",
        icon: <IconGoogleBW width={24} height={24} />,
        label: "Sign in with Google",
      },
      {
        backgroundColor: "#FFFFFF",
        borderColor: "#D0D5DD",
        foregroundColor: "#344054",
        icon: <IconGoogleBW width={24} height={24} />,
      },
    ],
    [
      {
        backgroundColor: "#FFFFFF",
        borderColor: "#D0D5DD",
        foregroundColor: "#344054",
        icon: <IconGoogleColorful width={24} height={24} />,
        label: "Sign in with Google",
      },
      {
        backgroundColor: "#FFFFFF",
        borderColor: "#D0D5DD",
        foregroundColor: "#344054",
        icon: <IconGoogleColorful width={24} height={24} />,
      },
      {
        backgroundColor: "#FFFFFF",
        borderColor: "#D0D5DD",
        foregroundColor: "#344054",
        icon: <IconGoogleColorful width={24} height={24} />,
        label: "Sign in with Google",
      },
      {
        backgroundColor: "#FFFFFF",
        borderColor: "#D0D5DD",
        foregroundColor: "#344054",
        icon: <IconGoogleColorful width={24} height={24} />,
      },
      {
        backgroundColor: "#FFFFFF",
        borderColor: "#D0D5DD",
        foregroundColor: "#344054",
        icon: <IconGoogleBW width={24} height={24} />,
        label: "Sign in with Google",
      },
      {
        backgroundColor: "#FFFFFF",
        borderColor: "#D0D5DD",
        foregroundColor: "#344054",
        icon: <IconGoogleBW width={24} height={24} />,
      },
    ],
    [
      {
        backgroundColor: "#FFFFFF",
        borderColor: "#D0D5DD",
        foregroundColor: "#344054",
        icon: <IconGoogleColorful width={24} height={24} />,
        label: "Sign in with Google",
      },
      {
        backgroundColor: "#FFFFFF",
        borderColor: "#D0D5DD",
        foregroundColor: "#344054",
        icon: <IconGoogleColorful width={24} height={24} />,
      },
      {
        backgroundColor: "#FFFFFF",
        borderColor: "#D0D5DD",
        foregroundColor: "#344054",
        icon: <IconGoogleColorful width={24} height={24} />,
        label: "Sign in with Google",
      },
      {
        backgroundColor: "#FFFFFF",
        borderColor: "#D0D5DD",
        foregroundColor: "#344054",
        icon: <IconGoogleColorful width={24} height={24} />,
      },
      {
        backgroundColor: "#FFFFFF",
        borderColor: "#D0D5DD",
        foregroundColor: "#344054",
        icon: <IconGoogleBW width={24} height={24} />,
        label: "Sign in with Google",
      },
      {
        backgroundColor: "#FFFFFF",
        borderColor: "#D0D5DD",
        foregroundColor: "#344054",
        icon: <IconGoogleBW width={24} height={24} />,
      },
    ],
  ],
];
